version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/suricata_db
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: suricata_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  openvas:
    image: greenbone/openvas
    ports:
      - "9392:9392"

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: host
    volumes:
      - ./suricata-config:/etc/suricata
    command: -i eth0

volumes:
  postgres_data: